export type Legalities = {
  alchemy?: string;
  brawl?: string;
  commander?: string;
  duel?: string;
  explorer?: string;
  future?: string;
  gladiator?: string;
  historic?: string;
  historicbrawl?: string;
  legacy?: string;
  modern?: string;
  oldschool?: string;
  pauper?: string;
  penny?: string;
  pioneer?: string;
  premodern?: string;
  standard?: string;
  vintage?: string;
};