name: Test and Build Application

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  build:
    name: 'Test and Build Application'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: |
        npm install

    - name: Test and build project
      run: |
        npm run test:full
      env:
        CI: true

    - uses: codecov/codecov-action@v1
      name: Upload code coverage
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
